UPDATE turista SET NOMBRE = 'Jose' WHERE turisid = 120;
UPDATE HOTEL SET NOMBRE = 'Hostal Botafumeiro' WHERE ID_HOTEL = 43;
UPDATE HOTEL SET TELEFONO = 983780209 WHERE ID_HOTEL = 43;
UPDATE HOTEL SET DIRECCION = 'Carr. Madrid-Corunna, Km 203' WHERE ID_HOTEL = 43;